/**
 * Embeds the built game into the app as a JS module.
 *
 * The app renders the game in a WebView, so the HTML has to ship inside the
 * bundle rather than be fetched -- there is no network where this runs. Writing
 * it as a generated .ts module means Metro handles it like any other import and
 * we do not have to fight expo-asset over a file it would rather stream.
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const protoDir = join(here, '..', '..', 'proto');

execFileSync('node', [join(protoDir, 'build.mjs')], { stdio: 'inherit' });
const html = readFileSync(join(protoDir, 'dist', 'tanks-proto.html'), 'utf8');

const outDir = join(here, '..', 'src', 'generated');
mkdirSync(outDir, { recursive: true });

// JSON.stringify handles every escape the HTML can contain -- backticks,
// backslashes, newlines, and the `</script>` sequence -- without us hand-rolling
// an escaper that will eventually get one of them wrong.
writeFileSync(
  join(outDir, 'gameHtml.ts'),
  `// Generated by scripts/embed-game.mjs. Do not edit.\n` +
    `export const GAME_HTML = ${JSON.stringify(html)};\n`,
);

console.log(`  embedded game: ${(html.length / 1024).toFixed(1)} KB`);
