/**
 * Builds the installable, offline-capable web app.
 *
 * The plain build emits a document *fragment* -- no <html>, <head> or <body> --
 * because that is what the artifact host wants. A real site needs the full
 * document, plus the three things that make a page installable and offline:
 *
 *   manifest.webmanifest  name, icons, landscape orientation, standalone display
 *   sw.js                 a service worker that caches everything on install
 *   apple-touch-icon      iOS ignores the manifest icons for the home screen
 *
 * Offline is the whole point. Once the service worker has installed, the page
 * loads from cache with the network unreachable -- aeroplane, tunnel, nowhere.
 * The game itself never needed the network; this is only about the browser
 * being willing to open it.
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'pwa');

mkdirSync(outDir, { recursive: true });

// The game itself, as a self-contained fragment.
execFileSync('node', [join(here, 'build.mjs')], { stdio: 'inherit' });
const fragment = readFileSync(join(here, 'dist', 'tanks-proto.html'), 'utf8');

// Icons, drawn procedurally so the palette stays in sync with the game.
execFileSync('python3', [join(here, 'icon.py'), outDir], { stdio: 'inherit' });

/**
 * Cache version.
 *
 * Derived from the content, so a rebuild that changes nothing does not evict
 * the cache, and a rebuild that changes anything guarantees every client
 * refetches. A hand-bumped version number is the classic way to ship a service
 * worker that serves last week's build forever.
 */
const version = createHash('sha256').update(fragment).digest('hex').slice(0, 12);

const manifest = {
  name: 'Tanks!',
  short_name: 'Tanks!',
  description: 'Ricochet tank battles. Works offline.',
  start_url: './',
  scope: './',
  display: 'fullscreen',
  // The arena is 24x14; portrait would waste most of the screen and shrink the
  // board below the point where you can read a bank shot coming.
  orientation: 'landscape',
  background_color: '#16140F',
  theme_color: '#16140F',
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
writeFileSync(join(outDir, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));

const sw = `/* Generated by build-pwa.mjs. Cache version: ${version} */
const CACHE = 'tanks-${version}';
const ASSETS = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icon-192.png',
  './icon-512.png',
  './apple-touch-icon.png',
];

// Precache everything up front. The game is one file, so there is no reason to
// lazily populate and risk the player going offline mid-session with a partial
// cache.
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cache-first. The content is versioned into the cache name, so a stale hit is
// impossible after activate -- and offline is the common case, not the
// exception, so going to the network first would add a timeout to every load.
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).catch(() =>
        // A navigation that misses the cache and has no network still has to
        // render something; fall back to the app shell.
        e.request.mode === 'navigate' ? caches.match('./index.html') : Promise.reject(),
      );
    }),
  );
});
`;
writeFileSync(join(outDir, 'sw.js'), sw);

const head = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no">
<meta name="theme-color" content="#16140F">
<meta name="description" content="Ricochet tank battles. Works offline.">
<link rel="manifest" href="manifest.webmanifest">
<!-- iOS ignores the manifest for home-screen installs and uses these instead. -->
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Tanks!">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
</head>
<body>
`;

const tail = `
<script>
  // Registration failure is not fatal -- the page still works, it just will not
  // survive going offline. Opening the file directly (file://) has no service
  // worker support at all, which is expected and not worth an error.
  if ('serviceWorker' in navigator && location.protocol.startsWith('http')) {
    window.addEventListener('load', () => {
      navigator.serviceWorker.register('sw.js').catch((err) => {
        console.warn('offline support unavailable:', err.message);
      });
    });
  }
</script>
</body>
</html>
`;

writeFileSync(join(outDir, 'index.html'), head + fragment + tail);

// GitHub Pages runs Jekyll by default, which strips files it does not recognise.
writeFileSync(join(outDir, '.nojekyll'), '');

// Keep the standalone single-file build alongside it, so it can be downloaded
// and saved directly to a phone with no install step.
cpSync(join(here, 'dist', 'tanks-proto.html'), join(outDir, 'tanks.html'));

const bytes = readFileSync(join(outDir, 'index.html')).length;
console.log(`\n  pwa/  index.html ${(bytes / 1024).toFixed(1)} KB  cache ${version}`);
